// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Cp4RugGCevyexxtFDsXvgLrW9J8U1F4',
    appId: '1:121129729497:web:463cdd7ac824df35deadc8',
    messagingSenderId: '121129729497',
    projectId: 'construction-c0bfe',
    authDomain: 'construction-c0bfe.firebaseapp.com',
    storageBucket: 'construction-c0bfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARS6fWMLbyTgKrk-rcaF5Dbgkz71XuQXU',
    appId: '1:121129729497:android:eb252bd5bce7a7e1deadc8',
    messagingSenderId: '121129729497',
    projectId: 'construction-c0bfe',
    storageBucket: 'construction-c0bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcEzTgVvupDd5HvJte0J8Sr8tc3mcjEGw',
    appId: '1:121129729497:ios:07c96fb427252796deadc8',
    messagingSenderId: '121129729497',
    projectId: 'construction-c0bfe',
    storageBucket: 'construction-c0bfe.appspot.com',
    androidClientId: '121129729497-angt2dt3nv3qrdn6spqtcbqclks7a1n0.apps.googleusercontent.com',
    iosClientId: '121129729497-3b7aipob5dl7mkj132f8hacjj1f7166m.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpmandu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcEzTgVvupDd5HvJte0J8Sr8tc3mcjEGw',
    appId: '1:121129729497:ios:478f85d60e422c1bdeadc8',
    messagingSenderId: '121129729497',
    projectId: 'construction-c0bfe',
    storageBucket: 'construction-c0bfe.appspot.com',
    androidClientId: '121129729497-angt2dt3nv3qrdn6spqtcbqclks7a1n0.apps.googleusercontent.com',
    iosClientId: '121129729497-55ucru4cp2loku8dkgisc9qv4ovinsi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpmandu.RunnerTests',
  );
}
