// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCegjjJt0oMgB2ygWr2PXSRLmOqfRJXUVQ',
    appId: '1:573259900980:web:64c5467c65253b7d06c261',
    messagingSenderId: '573259900980',
    projectId: 'helpmandu',
    authDomain: 'helpmandu.firebaseapp.com',
    storageBucket: 'helpmandu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54Os0_2-nmvrafKJ6NZVqzow9GomT0zo',
    appId: '1:573259900980:android:1a14b045092b3e3606c261',
    messagingSenderId: '573259900980',
    projectId: 'helpmandu',
    storageBucket: 'helpmandu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmQjfNUZzVI_mx5zGrlbQ4NQaTRkRodZQ',
    appId: '1:573259900980:ios:1c4c05c79408e99506c261',
    messagingSenderId: '573259900980',
    projectId: 'helpmandu',
    storageBucket: 'helpmandu.appspot.com',
    iosClientId: '573259900980-gms0b9sb5gvgalnrd1sk7nl7fq079mb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpmandu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmQjfNUZzVI_mx5zGrlbQ4NQaTRkRodZQ',
    appId: '1:573259900980:ios:a818c68269c03a5206c261',
    messagingSenderId: '573259900980',
    projectId: 'helpmandu',
    storageBucket: 'helpmandu.appspot.com',
    iosClientId: '573259900980-09lu1sfm3oh6qreed54shjk1hn84h0vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpmandu.RunnerTests',
  );
}
